// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveHITL():Promise<void>;

export function ChatWithModel(arg1:string,arg2:string):Promise<string>;

export function DownloadModel(arg1:string):Promise<string>;

export function GetOllamaModels():Promise<Array<string>>;

export function GetOllamaPath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RejectHITL(arg1:string):Promise<void>;

export function RemoveModel(arg1:string):Promise<string>;

export function SelectFolder():Promise<string>;

export function StartUpgradePipeline(arg1:string):Promise<void>;

export function UpdateOllamaPath(arg1:string):Promise<boolean>;
