// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpgrade(arg1, arg2) {
  return window['go']['main']['App']['ApplyUpgrade'](arg1, arg2);
}

export function ApproveHITL() {
  return window['go']['main']['App']['ApproveHITL']();
}

export function ChatWithModel(arg1, arg2) {
  return window['go']['main']['App']['ChatWithModel'](arg1, arg2);
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function GetActiveCommit() {
  return window['go']['main']['App']['GetActiveCommit']();
}

export function GetActiveVersion() {
  return window['go']['main']['App']['GetActiveVersion']();
}

export function GetAgentModels() {
  return window['go']['main']['App']['GetAgentModels']();
}

export function GetOllamaModels() {
  return window['go']['main']['App']['GetOllamaModels']();
}

export function GetOllamaPath() {
  return window['go']['main']['App']['GetOllamaPath']();
}

export function GetTranslationLanguage() {
  return window['go']['main']['App']['GetTranslationLanguage']();
}

export function GetUpgradeHistory() {
  return window['go']['main']['App']['GetUpgradeHistory']();
}

export function LogClientEvent(arg1, arg2) {
  return window['go']['main']['App']['LogClientEvent'](arg1, arg2);
}

export function RejectHITL(arg1) {
  return window['go']['main']['App']['RejectHITL'](arg1);
}

export function RemoveModel(arg1) {
  return window['go']['main']['App']['RemoveModel'](arg1);
}

export function RollbackUpgrade(arg1) {
  return window['go']['main']['App']['RollbackUpgrade'](arg1);
}

export function SaveAgentModels(arg1) {
  return window['go']['main']['App']['SaveAgentModels'](arg1);
}

export function SaveTranslationLanguage(arg1) {
  return window['go']['main']['App']['SaveTranslationLanguage'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartUpgradePipeline(arg1) {
  return window['go']['main']['App']['StartUpgradePipeline'](arg1);
}

export function TranslateText(arg1, arg2, arg3) {
  return window['go']['main']['App']['TranslateText'](arg1, arg2, arg3);
}

export function UpdateOllamaPath(arg1) {
  return window['go']['main']['App']['UpdateOllamaPath'](arg1);
}
