// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveHITL() {
  return window['go']['main']['App']['ApproveHITL']();
}

export function ChatWithModel(arg1, arg2) {
  return window['go']['main']['App']['ChatWithModel'](arg1, arg2);
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function GetOllamaModels() {
  return window['go']['main']['App']['GetOllamaModels']();
}

export function GetOllamaPath() {
  return window['go']['main']['App']['GetOllamaPath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RejectHITL(arg1) {
  return window['go']['main']['App']['RejectHITL'](arg1);
}

export function RemoveModel(arg1) {
  return window['go']['main']['App']['RemoveModel'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartUpgradePipeline(arg1) {
  return window['go']['main']['App']['StartUpgradePipeline'](arg1);
}

export function UpdateOllamaPath(arg1) {
  return window['go']['main']['App']['UpdateOllamaPath'](arg1);
}
