// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vcs} from '../models';

export function ApplyUpgrade(arg1:string,arg2:string):Promise<void>;

export function ApproveHITL():Promise<void>;

export function ChatWithModel(arg1:string,arg2:string):Promise<string>;

export function DownloadModel(arg1:string):Promise<string>;

export function GetActiveCommit():Promise<string>;

export function GetActiveVersion():Promise<string>;

export function GetLatestVersion():Promise<string>;

export function GetOllamaModels():Promise<Array<string>>;

export function GetOllamaPath():Promise<string>;

export function GetUpgradeHistory():Promise<Array<vcs.UpgradeHistory>>;

export function Greet(arg1:string):Promise<string>;

export function RejectHITL(arg1:string):Promise<void>;

export function RemoveModel(arg1:string):Promise<string>;

export function RollbackUpgrade(arg1:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function StartUpgradePipeline(arg1:string):Promise<void>;

export function UpdateOllamaPath(arg1:string):Promise<boolean>;
