// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpgrade(arg1, arg2) {
  return window['go']['main']['App']['ApplyUpgrade'](arg1, arg2);
}

export function ApproveHITL() {
  return window['go']['main']['App']['ApproveHITL']();
}

export function ChatWithModel(arg1, arg2) {
  return window['go']['main']['App']['ChatWithModel'](arg1, arg2);
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function GetActiveCommit() {
  return window['go']['main']['App']['GetActiveCommit']();
}

export function GetActiveVersion() {
  return window['go']['main']['App']['GetActiveVersion']();
}

export function GetLatestVersion() {
  return window['go']['main']['App']['GetLatestVersion']();
}

export function GetOllamaModels() {
  return window['go']['main']['App']['GetOllamaModels']();
}

export function GetOllamaPath() {
  return window['go']['main']['App']['GetOllamaPath']();
}

export function GetUpgradeHistory() {
  return window['go']['main']['App']['GetUpgradeHistory']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RejectHITL(arg1) {
  return window['go']['main']['App']['RejectHITL'](arg1);
}

export function RemoveModel(arg1) {
  return window['go']['main']['App']['RemoveModel'](arg1);
}

export function RollbackUpgrade(arg1) {
  return window['go']['main']['App']['RollbackUpgrade'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SimulateApplyAndRestart(arg1, arg2) {
  return window['go']['main']['App']['SimulateApplyAndRestart'](arg1, arg2);
}

export function StartUpgradePipeline(arg1) {
  return window['go']['main']['App']['StartUpgradePipeline'](arg1);
}

export function UpdateOllamaPath(arg1) {
  return window['go']['main']['App']['UpdateOllamaPath'](arg1);
}
